dist: xenial

language: node_js
node_js:
  - '12'

cache:
  bundler: true
  directories:
    - node_modules

addons:
  chrome: stable

services:
  - xvfb

script: npm run ci

branches:
  only:
    - master