sudo: required
dist: trusty

language: node_js
node_js:
  - "12"

cache:
  bundler: true
  directories:
    - node_modules

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_install:
  - stty cols 80

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

branches:
  only:
    - "master"
