dist: xenial

language: node_js
node_js:
  - '14'

cache:
  bundler: true
  directories:
    - node_modules

addons:
  chrome: stable

services:
  - xvfb

before_install:
  - npm i -g npm@latest

branches:
  only:
    - master
