name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - name: Setup Chrome
              uses: browser-actions/setup-chrome@latest

            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run test:unit

            - name: Run TestCafe tests on headless Chrome
              uses: DevExpress/testcafe-action@latest
              with:
                  args: "chrome:headless test/e2e/*.test.js"
